/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CadPreview: typeof import('./src/components/CadPreview.vue')['default']
    CadShowById: typeof import('./src/components/CadShowById.vue')['default']
    CoefficientCertificate: typeof import('./src/components/coefficients/CoefficientCertificate.vue')['default']
    CoefficientCover: typeof import('./src/components/coefficients/CoefficientCover.vue')['default']
    CoefficientFinish: typeof import('./src/components/coefficients/CoefficientFinish.vue')['default']
    CoefficientOtk: typeof import('./src/components/coefficients/CoefficientOtk.vue')['default']
    CoefficientProcess: typeof import('./src/components/coefficients/CoefficientProcess.vue')['default']
    CoefficientQuantity: typeof import('./src/components/coefficients/CoefficientQuantity.vue')['default']
    CoefficientSize: typeof import('./src/components/coefficients/CoefficientSize.vue')['default']
    CoefficientTolerance: typeof import('./src/components/coefficients/CoefficientTolerance.vue')['default']
    CoefficientTooling: typeof import('./src/components/coefficients/CoefficientTooling.vue')['default']
    CoefficientType: typeof import('./src/components/coefficients/CoefficientType.vue')['default']
    DialogCall: typeof import('./src/components/dialog/DialogCall.vue')['default']
    DialogInfoPayment: typeof import('./src/components/dialog/DialogInfoPayment.vue')['default']
    DialogLogin: typeof import('./src/components/dialog/DialogLogin.vue')['default']
    DialogRegistration: typeof import('./src/components/dialog/DialogRegistration.vue')['default']
    Diameter: typeof import('./src/components/coefficients/Diameter.vue')['default']
    DocumentShowByIds: typeof import('./src/components/DocumentShowByIds.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Height: typeof import('./src/components/coefficients/Height.vue')['default']
    Length: typeof import('./src/components/coefficients/Length.vue')['default']
    MaterialMachining: typeof import('./src/components/materials/MaterialMachining.vue')['default']
    MaterialMilling: typeof import('./src/components/materials/MaterialMilling.vue')['default']
    MaterialPaint: typeof import('./src/components/materials/MaterialPaint.vue')['default']
    MaterialPlastic: typeof import('./src/components/materials/MaterialPlastic.vue')['default']
    PaintArea: typeof import('./src/components/coefficients/PaintArea.vue')['default']
    PaintColor: typeof import('./src/components/coefficients/PaintColor.vue')['default']
    PaintLakery: typeof import('./src/components/coefficients/PaintLakery.vue')['default']
    PaintPrepare: typeof import('./src/components/coefficients/PaintPrepare.vue')['default']
    PaintPrimer: typeof import('./src/components/coefficients/PaintPrimer.vue')['default']
    PaintType: typeof import('./src/components/coefficients/PaintType.vue')['default']
    PlasticPreparation: typeof import('./src/components/coefficients/PlasticPreparation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionAbility: typeof import('./src/components/sections/SectionAbility.vue')['default']
    SectionAbout: typeof import('./src/components/sections/SectionAbout.vue')['default']
    SectionAdvantages: typeof import('./src/components/sections/SectionAdvantages.vue')['default']
    SectionModel: typeof import('./src/components/sections/SectionModel.vue')['default']
    StpShowById: typeof import('./src/components/StpShowById.vue')['default']
    UploadDrawings: typeof import('./src/components/UploadDrawings.vue')['default']
    UploadModel: typeof import('./src/components/UploadModel.vue')['default']
    UpperMenu: typeof import('./src/components/UpperMenu.vue')['default']
    Width: typeof import('./src/components/coefficients/Width.vue')['default']
  }
}
